/* ═══════════════════════════════════════════════════════════
   YOURDIS DATA — v2.0
   20 products — bilingual (EN + AR) fields ready for i18n
═══════════════════════════════════════════════════════════ */

var YOURDIS_IMAGES = {
  chanel:'jpeg1.jpg', dior:'jpeg2.jpg', tomford:'jpeg3.jpg',
  ysl:'jpeg4.jpg', armani:'jpeg5.jpg', creed:'jpeg6.jpg',
  versace:'jpeg7.jpg', burberry:'jpeg8.jpg', paco:'jpeg9.jpg',
  lancome:'jpeg10.jpg', hermes:'jpeg11.jpg', guerlain:'jpeg12.jpg',
  jpgaultier:'jpeg13.jpg', isseymiyake:'jpeg14.jpg', bvlgari:'jpeg15.jpg',
  montblanc:'jpeg16.jpg', valentino:'jpeg17.jpg',
  carolinaherrera:'jpeg18.jpg', narciso:'jpeg19.jpg', dunhill:'jpeg20.jpg'
};

var PRODUCTS = {

  chanel:{
    name:'Bleu de Chanel EDP',brand:'Chanel · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.chanel,initials:'Cd',bg:'var(--b-purple)',
    name_ar:'بلو دو شانيل إي دي بي',brand_ar:'شانيل · 100 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Woody Aromatic',family_ar:'خشبي عطري',
    notes:'<span class="note-chip note-top">Top: Citrus · Bergamot</span><span class="note-chip note-heart">Heart: Vetiver · Cedarwood</span><span class="note-chip note-base">Base: Patchouli · Labdanum</span>',
    notes_ar:'قمة: حمضيات · برغموت · قلب: فيتيفر · خشب الأرز · قاعدة: باتشولي · لبدانم',
    desc:'A modern masculine icon. Citrus and bergamot open brightly before settling into a deep woody heart of vetiver and cedarwood. Patchouli and labdanum in the base create an elegant, lasting trail. Projection is confident with longevity exceeding 10 hours.',
    desc_ar:'أيقونة عصرية للرجل. تبدأ بالحمضيات والبرغموت قبل أن تستقر في قلب خشبي عميق. القاعدة الدافئة تمنح أثراً طويل الأمد يتجاوز 10 ساعات.',
    price:'485 SAR',orig:'620 SAR',store:'Golden Scent',storeKey:'amazon',
    badge:'↓ 22% off',badgeClass:'badge-fire',
    atl:'440 SAR',avg:'540 SAR',ath:'680 SAR',
    rating:'4.6',reviews:'287',
    r1:'Incredible longevity — 10+ hours. Found it for 485 SAR on Golden Scent thanks to Yourdis.',
    r2:'Classic for a reason. The EDP has better projection than the EDT. Great value.',
    priceHistory:[{date:'Today · 2 hrs ago',price:'485 SAR',dir:'down'},{date:'14 Feb 2025',price:'620 SAR',dir:'up'},{date:'02 Nov 2024',price:'460 SAR',dir:'down'},{date:'15 Aug 2024',price:'660 SAR',dir:'up'},{date:'01 Jun 2024',price:'510 SAR',dir:'down'}],
    storeComparison:[{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'485 SAR',diff:'Best price'},{key:'namshi',name:'Nice One',ship:'Free delivery · 2–3 days',price:'510 SAR',diff:'+25 SAR'},{key:'sephora',name:'Asheq Al-Otor',ship:'Delivery · 3–5 days',price:'545 SAR',diff:'+60 SAR'}]
  },

  dior:{
    name:'Dior Sauvage EDT',brand:'Dior · 200ml · Eau de Toilette',
    img:YOURDIS_IMAGES.dior,initials:'Dk',bg:'var(--b-teal)',
    name_ar:'ديور سوفاج إي دي تي',brand_ar:'ديور · 200 مل · ماء تواليت',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Fresh Spicy',family_ar:'منعش حار',
    notes:'<span class="note-chip note-top">Top: Calabrian Bergamot</span><span class="note-chip note-heart">Heart: Sichuan Pepper · Geranium</span><span class="note-chip note-base">Base: Ambroxan · Cedar</span>',
    notes_ar:'قمة: برغموت كالابريا · قلب: فلفل سيتشوان · قاعدة: أمبروكسان · أرز',
    desc:'Radically fresh and ruggedly clean. Calabrian bergamot opens on Sichuan pepper, anchored by mineral Ambroxan and cedar. Effortlessly versatile — boardroom to open skies. Longevity 8–10 hours.',
    desc_ar:'منعش وأنيق. يبدأ بالبرغموت الإيطالي ثم فلفل سيتشوان، مع قاعدة معدنية من الأمبروكسان والأرز. يدوم 8-10 ساعات.',
    price:'310 SAR',orig:'370 SAR',store:'Najd Al-Otheyah',storeKey:'noon',
    badge:'↓ 16% off',badgeClass:'badge-good',
    atl:'285 SAR',avg:'355 SAR',ath:'430 SAR',
    rating:'4.8',reviews:'1,203',
    r1:'Best-selling scent for a reason. Fresh, clean and beast-mode projection.',
    r2:'Versatile for office and evenings alike. This Yourdis alert saved me 60 SAR.',
    priceHistory:[{date:'Today · 5 hrs ago',price:'310 SAR',dir:'down'},{date:'20 Feb 2025',price:'370 SAR',dir:'up'},{date:'10 Nov 2024',price:'295 SAR',dir:'down'},{date:'01 Sep 2024',price:'400 SAR',dir:'up'},{date:'15 Jun 2024',price:'320 SAR',dir:'down'}],
    storeComparison:[{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'310 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'340 SAR',diff:'+30 SAR'},{key:'namshi',name:'Nice One',ship:'Delivery · 3–5 days',price:'365 SAR',diff:'+55 SAR'}]
  },

  tomford:{
    name:'Tom Ford Tobacco Oud EDP',brand:'Tom Ford · 50ml · Eau de Parfum',
    img:YOURDIS_IMAGES.tomford,initials:'Tf',bg:'var(--b-amber)',
    name_ar:'توم فورد توباكو عود إي دي بي',brand_ar:'توم فورد · 50 مل · عطر مركّز',
    country:'USA',country_ar:'الولايات المتحدة',gender:'Unisex',gender_ar:'للجنسين',
    family:'Oriental Oud',family_ar:'شرقي عود',
    notes:'<span class="note-chip note-top">Top: Clove · Coriander</span><span class="note-chip note-heart">Heart: Tobacco · Oud Wood</span><span class="note-chip note-base">Base: Sandalwood · Tonka Bean</span>',
    notes_ar:'قمة: قرنفل · كزبرة · قلب: تبغ · عود · قاعدة: صندل · فاصوليا التونكا',
    desc:'From the Private Blend collection — unapologetically opulent. Spiced clove and coriander give way to a rich heart of tobacco and oud. Sandalwood and tonka bean create creamy, enduring warmth. Longevity exceptional at 12+ hours.',
    desc_ar:'من مجموعة بلند خاص. يبدأ بالقرنفل المتبّل قبل قلب غني من التبغ والعود. قاعدة دافئة من الصندل وفاصوليا التونكا. يدوم 12 ساعة وأكثر.',
    price:'590 SAR',orig:'650 SAR',store:'Laudour',storeKey:'sephora',
    badge:'↓ 9% off',badgeClass:'badge-good',
    atl:'560 SAR',avg:'640 SAR',ath:'750 SAR',
    rating:'4.5',reviews:'342',
    r1:'The definition of luxury. Oud lovers will not be disappointed. Worth every riyal.',
    r2:'Massive projection, lasts all day. A true statement fragrance.',
    priceHistory:[{date:'Today · 3 hrs ago',price:'590 SAR',dir:'down'},{date:'10 Mar 2025',price:'650 SAR',dir:'up'},{date:'05 Dec 2024',price:'580 SAR',dir:'down'},{date:'20 Sep 2024',price:'720 SAR',dir:'up'},{date:'01 Jul 2024',price:'600 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Laudour',ship:'Free delivery · 2–3 days',price:'590 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'620 SAR',diff:'+30 SAR'},{key:'centrepoint',name:'Deraah',ship:'Delivery · 4–6 days',price:'645 SAR',diff:'+55 SAR'}]
  },

  ysl:{
    name:'YSL Y Le Parfum',brand:'Yves Saint Laurent · 60ml · Parfum',
    img:YOURDIS_IMAGES.ysl,initials:'YS',bg:'var(--b-pink)',
    name_ar:'إيف سان لوران واي لو بارفان',brand_ar:'إيف سان لوران · 60 مل · بارفان',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Fougere Aromatic',family_ar:'فوجير عطري',
    notes:'<span class="note-chip note-top">Top: Bergamot · Ginger</span><span class="note-chip note-heart">Heart: Sage · Suede</span><span class="note-chip note-base">Base: Fir Balsam · Ambergris</span>',
    notes_ar:'قمة: برغموت · زنجبيل · قلب: مريمية · شمواه · قاعدة: بلسم تنوب · عنبر',
    desc:'Y Le Parfum deepens the iconic Y DNA considerably. Bergamot and ginger open brightly before sage and suede create a dry, sophisticated heart. Fir balsam and ambergris carry the scent from day into night. Longevity 8–10 hours.',
    desc_ar:'يعمّق تركيبة Y الأيقونية. يبدأ بالبرغموت والزنجبيل، ثم قلب من المريمية والشمواه الجاف. يمتد من النهار إلى الليل بأناقة. يدوم 8-10 ساعات.',
    price:'290 SAR',orig:'350 SAR',store:'V Perfume',storeKey:'jarir',
    badge:'↓ 17% off',badgeClass:'badge-good',
    atl:'265 SAR',avg:'330 SAR',ath:'390 SAR',
    rating:'4.4',reviews:'518',
    r1:'Fresh and modern. The suede note really comes out on skin.',
    r2:'Great office scent. Picked it up at V Perfume for 290 SAR.',
    priceHistory:[{date:'Today · 5 hrs ago',price:'290 SAR',dir:'down'},{date:'01 Mar 2025',price:'350 SAR',dir:'up'},{date:'15 Nov 2024',price:'275 SAR',dir:'down'},{date:'10 Aug 2024',price:'380 SAR',dir:'up'},{date:'20 May 2024',price:'295 SAR',dir:'down'}],
    storeComparison:[{key:'jarir',name:'V Perfume',ship:'Free delivery · 2–3 days',price:'290 SAR',diff:'Best price'},{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'315 SAR',diff:'+25 SAR'},{key:'amazon',name:'Golden Scent',ship:'Delivery · 3–5 days',price:'340 SAR',diff:'+50 SAR'}]
  },

  armani:{
    name:'Acqua di Gio EDP',brand:'Armani · 75ml · Eau de Parfum',
    img:YOURDIS_IMAGES.armani,initials:'Aq',bg:'var(--b-blue)',
    name_ar:'أكوا دي جيو إي دي بي',brand_ar:'أرماني · 75 مل · عطر مركّز',
    country:'Italy',country_ar:'إيطاليا',gender:'Men',gender_ar:'رجالي',
    family:'Fresh Aquatic',family_ar:'مائي منعش',
    notes:'<span class="note-chip note-top">Top: Marine Accord · Bergamot</span><span class="note-chip note-heart">Heart: Incense · Rosemary</span><span class="note-chip note-base">Base: Patchouli · Mineral Amber</span>',
    notes_ar:'قمة: ألحان بحرية · برغموت · قلب: بخور · روزماري · قاعدة: باتشولي · عنبر معدني',
    desc:'Elevates the legendary original with deeper character. Marine accord and bergamot open fresh before incense and rosemary add meditative depth. Patchouli and mineral amber anchor the drydown beautifully. Longevity 9–11 hours.',
    desc_ar:'يرفع الأصل الأسطوري بعمق أكبر. الألحان البحرية والبرغموت يفتحان بنعومة، قبل أن يضيف البخور والروزماري عمقاً تأملياً. يدوم 9-11 ساعة.',
    price:'265 SAR',orig:'350 SAR',store:'Al-Sultan Perfumes',storeKey:'namshi',
    badge:'↓ 24% off',badgeClass:'badge-fire',
    atl:'250 SAR',avg:'315 SAR',ath:'380 SAR',
    rating:'4.7',reviews:'892',
    r1:'Better than the EDT in every way. The incense adds depth without losing freshness.',
    r2:'Yourdis caught this at the lowest price I\'ve seen. Grabbed two bottles!',
    priceHistory:[{date:'Today · 1 hr ago',price:'265 SAR',dir:'down'},{date:'25 Feb 2025',price:'350 SAR',dir:'up'},{date:'20 Oct 2024',price:'255 SAR',dir:'down'},{date:'05 Aug 2024',price:'370 SAR',dir:'up'},{date:'10 Apr 2024',price:'280 SAR',dir:'down'}],
    storeComparison:[{key:'namshi',name:'Al-Sultan Perfumes',ship:'Free delivery · 1–2 days',price:'265 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'290 SAR',diff:'+25 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'310 SAR',diff:'+45 SAR'}]
  },

  creed:{
    name:'Creed Aventus',brand:'Creed · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.creed,initials:'Cr',bg:'var(--b-sage)',
    name_ar:'كريد أفينتوس',brand_ar:'كريد · 100 مل · عطر مركّز',
    country:'UK',country_ar:'المملكة المتحدة',gender:'Men',gender_ar:'رجالي',
    family:'Woody Fruity',family_ar:'خشبي فاكهي',
    notes:'<span class="note-chip note-top">Top: Blackcurrant · Bergamot · Apple</span><span class="note-chip note-heart">Heart: Birch · Jasmine · Rose</span><span class="note-chip note-base">Base: Musk · Oakmoss · Ambergris</span>',
    notes_ar:'قمة: كشمش أسود · برغموت · تفاح · قلب: بتولا · ياسمين · ورد · قاعدة: مسك · طحلب · عنبر',
    desc:'The fragrance that defined a generation. Blackcurrant, bergamot and apple create a triumphant opening yielding to smoky birch. Musk, oakmoss and ambergris ensure remarkable longevity. Every batch carries subtle variation. Longevity 10–14 hours.',
    desc_ar:'العطر الذي عرّف جيلاً. يفتح بالكشمش الأسود والبرغموت والتفاح، ثم يستقر على البتولا المدخّنة. كل دفعة تحمل تمييزاً خفياً. يدوم 10-14 ساعة.',
    price:'840 SAR',orig:'1,050 SAR',store:'Asheq Al-Otor',storeKey:'sephora',
    badge:'↓ 20% off',badgeClass:'badge-fire',
    atl:'810 SAR',avg:'990 SAR',ath:'1,150 SAR',
    rating:'4.9',reviews:'2,104',
    r1:'The king of fragrances. Every batch has slight variation which makes each bottle unique.',
    r2:'840 SAR is an absolute steal for 100ml Aventus. Yourdis alert worked perfectly.',
    priceHistory:[{date:'Today · 2 days ago',price:'840 SAR',dir:'down'},{date:'01 Mar 2025',price:'1,050 SAR',dir:'up'},{date:'10 Nov 2024',price:'820 SAR',dir:'down'},{date:'15 Jul 2024',price:'1,100 SAR',dir:'up'},{date:'01 Apr 2024',price:'860 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'840 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'895 SAR',diff:'+55 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'1,050 SAR',diff:'+210 SAR'}]
  },

  versace:{
    name:'Versace Eros EDP',brand:'Versace · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.versace,initials:'Ve',bg:'var(--b-pink)',
    name_ar:'فيرساتشي إيروس إي دي بي',brand_ar:'فيرساتشي · 100 مل · عطر مركّز',
    country:'Italy',country_ar:'إيطاليا',gender:'Men',gender_ar:'رجالي',
    family:'Oriental Fougere',family_ar:'شرقي فوجير',
    notes:'<span class="note-chip note-top">Top: Mint · Green Apple · Lemon</span><span class="note-chip note-heart">Heart: Tonka Bean · Geranium</span><span class="note-chip note-base">Base: Vanilla · Oakmoss · Vetiver</span>',
    notes_ar:'قمة: نعنع · تفاح أخضر · ليمون · قلب: تونكا · جيرانيوم · قاعدة: فانيليا · طحلب · فيتيفر',
    desc:'Inspired by the Greek god of love, Eros opens with a burst of mint and green apple before a warm, sensual base of vanilla and oakmoss. Confident and seductive — a modern classic for evening wear. Longevity 8–10 hours.',
    desc_ar:'مستوحى من إله الحب الإغريقي. يفتح بالنعنع والتفاح الأخضر ثم قاعدة دافئة من الفانيليا وطحلب البلوط. مثالي لأمسيات الشتاء. يدوم 8-10 ساعات.',
    price:'345 SAR',orig:'420 SAR',store:'Golden Scent',storeKey:'amazon',
    badge:'↓ 18% off',badgeClass:'badge-good',
    atl:'310 SAR',avg:'390 SAR',ath:'450 SAR',
    rating:'4.3',reviews:'674',
    r1:'Better projection than the EDT. The mint opening is addictive.',
    r2:'Excellent evening scent at this price.',
    priceHistory:[{date:'Today · 4 hrs ago',price:'345 SAR',dir:'down'},{date:'15 Feb 2025',price:'420 SAR',dir:'up'},{date:'01 Nov 2024',price:'330 SAR',dir:'down'},{date:'10 Aug 2024',price:'440 SAR',dir:'up'},{date:'20 May 2024',price:'360 SAR',dir:'down'}],
    storeComparison:[{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'345 SAR',diff:'Best price'},{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'370 SAR',diff:'+25 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'395 SAR',diff:'+50 SAR'}]
  },

  burberry:{
    name:'Burberry Hero EDP',brand:'Burberry · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.burberry,initials:'Bh',bg:'var(--b-teal)',
    name_ar:'بربري هيرو إي دي بي',brand_ar:'بربري · 100 مل · عطر مركّز',
    country:'UK',country_ar:'المملكة المتحدة',gender:'Men',gender_ar:'رجالي',
    family:'Woody Fresh',family_ar:'خشبي منعش',
    notes:'<span class="note-chip note-top">Top: Juniper · Cedar Leaf</span><span class="note-chip note-heart">Heart: Sandalwood · Black Pepper</span><span class="note-chip note-base">Base: Benzoin · Ambergris</span>',
    notes_ar:'قمة: عرعر · أوراق الأرز · قلب: صندل · فلفل أسود · قاعدة: بنزوين · عنبر',
    desc:'Hero EDP captures the spirit of adventure and strength. Juniper and cedar open with cool freshness before sandalwood and black pepper bring warmth and depth. Benzoin and ambergris deliver a grounding, masculine base. Longevity 7–9 hours.',
    desc_ar:'يجسّد روح المغامرة والقوة. العرعر والأرز يفتحان ببرودة منعشة قبل أن يضيف الصندل والفلفل الأسود الدفء والعمق. يدوم 7-9 ساعات.',
    price:'280 SAR',orig:'340 SAR',store:'Al-Sultan Perfumes',storeKey:'namshi',
    badge:'↓ 18% off',badgeClass:'badge-good',
    atl:'255 SAR',avg:'310 SAR',ath:'365 SAR',
    rating:'4.2',reviews:'389',
    r1:'Underrated gem. The pepper note keeps it interesting all day.',
    r2:'Solid daily driver. Great performance for the price.',
    priceHistory:[{date:'Today · 6 hrs ago',price:'280 SAR',dir:'down'},{date:'20 Feb 2025',price:'340 SAR',dir:'up'},{date:'05 Dec 2024',price:'265 SAR',dir:'down'},{date:'01 Sep 2024',price:'355 SAR',dir:'up'},{date:'15 Jun 2024',price:'290 SAR',dir:'down'}],
    storeComparison:[{key:'namshi',name:'Al-Sultan Perfumes',ship:'Free delivery · 1–2 days',price:'280 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'300 SAR',diff:'+20 SAR'},{key:'jarir',name:'V Perfume',ship:'Delivery · 3–5 days',price:'325 SAR',diff:'+45 SAR'}]
  },

  paco:{
    name:'Paco Rabanne 1 Million EDP',brand:'Paco Rabanne · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.paco,initials:'1M',bg:'var(--b-amber)',
    name_ar:'باكو رابان ون مليون إي دي بي',brand_ar:'باكو رابان · 100 مل · عطر مركّز',
    country:'Spain',country_ar:'إسبانيا',gender:'Men',gender_ar:'رجالي',
    family:'Oriental Spicy',family_ar:'شرقي حار',
    notes:'<span class="note-chip note-top">Top: Grapefruit · Mint · Mandarin</span><span class="note-chip note-heart">Heart: Cinnamon · Spices · Rose</span><span class="note-chip note-base">Base: Leather · Amber · Woody</span>',
    notes_ar:'قمة: جريب فروت · نعنع · ماندرين · قلب: قرفة · بهارات · ورد · قاعدة: جلد · عنبر · خشب',
    desc:'1 Million EDP intensifies the iconic gold bar bottle with even more richness. A luminous opening of grapefruit and mandarin transitions to a spiced leather heart. The base is opulent, warm and magnetic — made for evening occasions. Longevity 10+ hours.',
    desc_ar:'يكثّف الزجاجة الذهبية الأيقونية بمزيد من الفخامة. يفتح بالجريب فروت والماندرين قبل قلب جلدي متبّل. القاعدة دافئة وجاذبة. يدوم 10 ساعات وأكثر.',
    price:'320 SAR',orig:'395 SAR',store:'Asheq Al-Otor',storeKey:'sephora',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'295 SAR',avg:'365 SAR',ath:'420 SAR',
    rating:'4.4',reviews:'761',
    r1:'Way better than the original EDT. Richer, longer lasting and more refined.',
    r2:'Compliment machine. People ask what I\'m wearing every single time.',
    priceHistory:[{date:'Today · 3 hrs ago',price:'320 SAR',dir:'down'},{date:'10 Mar 2025',price:'395 SAR',dir:'up'},{date:'20 Nov 2024',price:'305 SAR',dir:'down'},{date:'15 Aug 2024',price:'415 SAR',dir:'up'},{date:'01 May 2024',price:'330 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'320 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'345 SAR',diff:'+25 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'370 SAR',diff:'+50 SAR'}]
  },

  lancome:{
    name:'Lancome Idole EDP',brand:'Lancome · 75ml · Eau de Parfum',
    img:YOURDIS_IMAGES.lancome,initials:'Id',bg:'var(--b-purple)',
    name_ar:'لانكوم إيدول إي دي بي',brand_ar:'لانكوم · 75 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Women',gender_ar:'نسائي',
    family:'Floral Musky',family_ar:'زهري مسكي',
    notes:'<span class="note-chip note-top">Top: Bergamot · Pear</span><span class="note-chip note-heart">Heart: Rose · Jasmine</span><span class="note-chip note-base">Base: Musk · Patchouli</span>',
    notes_ar:'قمة: برغموت · إجاص · قلب: ورد · ياسمين · قاعدة: مسك · باتشولي',
    desc:'A modern floral for the woman who leads. Crisp pear and bergamot brighten into a lush rose and jasmine heart. Musk and patchouli give it a contemporary, clean finish. Light and wearable from morning to evening. Longevity 7–8 hours.',
    desc_ar:'زهري عصري للمرأة القائدة. الإجاص والبرغموت يفتحان ثم ورد وياسمين غنيان. المسك والباتشولي يمنحانه نهاية نظيفة. يدوم 7-8 ساعات.',
    price:'295 SAR',orig:'370 SAR',store:'Golden Scent',storeKey:'amazon',
    badge:'↓ 20% off',badgeClass:'badge-good',
    atl:'270 SAR',avg:'340 SAR',ath:'395 SAR',
    rating:'4.5',reviews:'512',
    r1:'The most wearable floral I own. Fresh but with real depth.',
    r2:'Perfect office fragrance. Light enough not to overwhelm.',
    priceHistory:[{date:'Today · 2 hrs ago',price:'295 SAR',dir:'down'},{date:'05 Mar 2025',price:'370 SAR',dir:'up'},{date:'10 Dec 2024',price:'280 SAR',dir:'down'},{date:'20 Sep 2024',price:'385 SAR',dir:'up'},{date:'01 Jun 2024',price:'305 SAR',dir:'down'}],
    storeComparison:[{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'295 SAR',diff:'Best price'},{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'315 SAR',diff:'+20 SAR'},{key:'namshi',name:'Al-Sultan Perfumes',ship:'Delivery · 3–5 days',price:'340 SAR',diff:'+45 SAR'}]
  },

  hermes:{
    name:'Hermes Terre dHermes EDP',brand:'Hermes · 75ml · Eau de Parfum',
    img:YOURDIS_IMAGES.hermes,initials:'Hr',bg:'var(--b-amber)',
    name_ar:'هيرميس تير ديرميس إي دي بي',brand_ar:'هيرميس · 75 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Woody Earthy',family_ar:'خشبي ترابي',
    notes:'<span class="note-chip note-top">Top: Grapefruit · Orange</span><span class="note-chip note-heart">Heart: Pepper · Geranium · Vetiver</span><span class="note-chip note-base">Base: Flint · Cedar · Benzoin</span>',
    notes_ar:'قمة: جريب فروت · برتقال · قلب: فلفل · جيرانيوم · فيتيفر · قاعدة: صوان · أرز · بنزوين',
    desc:'A mineral, earthy masterpiece. Bright citrus gives way to a rich heart of pepper and vetiver before flint and cedar create a raw, rocky base. Beautifully conceptual — land, minerals and sky in a bottle. Longevity 8–10 hours.',
    desc_ar:'تحفة معدنية وترابية. يفتح بالحمضيات المشرقة ثم قلب من الفلفل والفيتيفر، قبل قاعدة صخرية من الصوان والأرز. يدوم 8-10 ساعات.',
    price:'380 SAR',orig:'455 SAR',store:'Asheq Al-Otor',storeKey:'sephora',
    badge:'↓ 17% off',badgeClass:'badge-good',
    atl:'350 SAR',avg:'425 SAR',ath:'490 SAR',
    rating:'4.6',reviews:'441',
    r1:'One of the most intellectual fragrances ever made. A wearable work of art.',
    r2:'Gets better every hour. The drydown is extraordinary.',
    priceHistory:[{date:'Today · 1 hr ago',price:'380 SAR',dir:'down'},{date:'28 Feb 2025',price:'455 SAR',dir:'up'},{date:'15 Nov 2024',price:'365 SAR',dir:'down'},{date:'01 Aug 2024',price:'470 SAR',dir:'up'},{date:'10 Apr 2024',price:'390 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'380 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'405 SAR',diff:'+25 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'430 SAR',diff:'+50 SAR'}]
  },

  guerlain:{
    name:'Guerlain Mon Guerlain EDP',brand:'Guerlain · 100ml · Eau de Parfum',
    img:YOURDIS_IMAGES.guerlain,initials:'Gu',bg:'var(--b-sage)',
    name_ar:'غيرلان مون غيرلان إي دي بي',brand_ar:'غيرلان · 100 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Women',gender_ar:'نسائي',
    family:'Floral Gourmand',family_ar:'زهري شهي',
    notes:'<span class="note-chip note-top">Top: Bergamot · Lavender</span><span class="note-chip note-heart">Heart: Jasmine · Peony</span><span class="note-chip note-base">Base: Sandalwood · Tahitian Vanilla</span>',
    notes_ar:'قمة: برغموت · لافندر · قلب: ياسمين · أوزة · قاعدة: صندل · فانيليا تاهيتية',
    desc:'A romantic, modern fragrance inspired by the south of France. Lavender and bergamot open gently before a floral heart of jasmine and peony. Tahitian vanilla in the base is creamy and warm — intimate and effortlessly feminine. Longevity 8–9 hours.',
    desc_ar:'عطر رومانسي مستوحى من جنوب فرنسا. اللافندر والبرغموت يفتحان بلطف، ثم قلب زهري من الياسمين والأوزة. الفانيليا التاهيتية دافئة وحميمة. يدوم 8-9 ساعات.',
    price:'270 SAR',orig:'330 SAR',store:'Najd Al-Otheyah',storeKey:'noon',
    badge:'↓ 18% off',badgeClass:'badge-good',
    atl:'245 SAR',avg:'305 SAR',ath:'360 SAR',
    rating:'4.4',reviews:'387',
    r1:'The vanilla is not heavy at all — very elegant and refined.',
    r2:'A classic Guerlain that punches above its weight in longevity.',
    priceHistory:[{date:'Today · 3 hrs ago',price:'270 SAR',dir:'down'},{date:'01 Mar 2025',price:'330 SAR',dir:'up'},{date:'10 Dec 2024',price:'255 SAR',dir:'down'},{date:'15 Sep 2024',price:'345 SAR',dir:'up'},{date:'20 May 2024',price:'280 SAR',dir:'down'}],
    storeComparison:[{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'270 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'290 SAR',diff:'+20 SAR'},{key:'sephora',name:'Asheq Al-Otor',ship:'Delivery · 3–5 days',price:'315 SAR',diff:'+45 SAR'}]
  },

  jpgaultier:{
    name:'Jean Paul Gaultier Le Male EDP',brand:'Jean Paul Gaultier · 75ml · EDP',
    img:YOURDIS_IMAGES.jpgaultier,initials:'LM',bg:'var(--b-pink)',
    name_ar:'جان بول غوتييه لو مال إي دي بي',brand_ar:'جان بول غوتييه · 75 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Oriental Fougere',family_ar:'شرقي فوجير',
    notes:'<span class="note-chip note-top">Top: Lavender · Bergamot · Cardamom</span><span class="note-chip note-heart">Heart: Cinnamon · Iris · Amber</span><span class="note-chip note-base">Base: Vanilla · Sandalwood · Musk</span>',
    notes_ar:'قمة: لافندر · برغموت · هيل · قلب: قرفة · أيريس · عنبر · قاعدة: فانيليا · صندل · مسك',
    desc:'Le Male EDP takes the iconic original and amplifies every element. Lavender and cardamom open boldly before a sweet, warm heart of cinnamon and amber. The vanilla and sandalwood base is rich and sensual. Longevity 10+ hours.',
    desc_ar:'يأخذ الأصل الأيقوني ويضخّم كل عنصر. اللافندر والهيل يفتحان بجرأة، ثم قلب دافئ من القرفة والعنبر. قاعدة الفانيليا والصندل غنية وحسية. يدوم 10 ساعات وأكثر.',
    price:'260 SAR',orig:'320 SAR',store:'Asheq Al-Otor',storeKey:'sephora',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'235 SAR',avg:'295 SAR',ath:'345 SAR',
    rating:'4.3',reviews:'298',
    r1:'The EDP version is in a different league from the EDT. Much richer.',
    r2:'Timeless. I keep coming back to this every winter.',
    priceHistory:[{date:'Today · 5 hrs ago',price:'260 SAR',dir:'down'},{date:'15 Feb 2025',price:'320 SAR',dir:'up'},{date:'20 Nov 2024',price:'245 SAR',dir:'down'},{date:'01 Aug 2024',price:'335 SAR',dir:'up'},{date:'10 Apr 2024',price:'265 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'260 SAR',diff:'Best price'},{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'280 SAR',diff:'+20 SAR'},{key:'amazon',name:'Golden Scent',ship:'Delivery · 3–5 days',price:'300 SAR',diff:'+40 SAR'}]
  },

  isseymiyake:{
    name:'Issey Miyake Leau dIssey EDT',brand:'Issey Miyake · 100ml · EDT',
    img:YOURDIS_IMAGES.isseymiyake,initials:'Iy',bg:'var(--b-teal)',
    name_ar:'إيسي مياكي لو دو إيسي إي دي تي',brand_ar:'إيسي مياكي · 100 مل · ماء تواليت',
    country:'Japan',country_ar:'اليابان',gender:'Women',gender_ar:'نسائي',
    family:'Aquatic Floral',family_ar:'مائي زهري',
    notes:'<span class="note-chip note-top">Top: Cyclamen · Lotus · Calone</span><span class="note-chip note-heart">Heart: Lily · Freesia · Carnation</span><span class="note-chip note-base">Base: Sandalwood · Musk · Amber</span>',
    notes_ar:'قمة: سيكلامن · لوتس · كالون · قلب: زنبق · فريزيا · قرنفل · قاعدة: صندل · مسك · عنبر',
    desc:'The archetypal clean aquatic floral — a landmark of modern perfumery that still feels contemporary. Watery lotus and cyclamen open before a delicate floral heart. The base is soft, white and skin-like. Ideal for warm days. Longevity 5–7 hours.',
    desc_ar:'النموذج الأصلي للعطر المائي الزهري النظيف. اللوتس المائي والسيكلامن يفتحان قبل قلب زهري رقيق. مثالي للأيام الدافئة. يدوم 5-7 ساعات.',
    price:'195 SAR',orig:'245 SAR',store:'V Perfume',storeKey:'jarir',
    badge:'↓ 20% off',badgeClass:'badge-good',
    atl:'175 SAR',avg:'220 SAR',ath:'265 SAR',
    rating:'4.2',reviews:'623',
    r1:'A classic that never gets old. Clean, fresh and universally loved.',
    r2:'Excellent value. Light and perfect for summer.',
    priceHistory:[{date:'Today · 2 hrs ago',price:'195 SAR',dir:'down'},{date:'20 Feb 2025',price:'245 SAR',dir:'up'},{date:'01 Nov 2024',price:'185 SAR',dir:'down'},{date:'15 Jul 2024',price:'260 SAR',dir:'up'},{date:'01 Apr 2024',price:'200 SAR',dir:'down'}],
    storeComparison:[{key:'jarir',name:'V Perfume',ship:'Free delivery · 2–3 days',price:'195 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'215 SAR',diff:'+20 SAR'},{key:'namshi',name:'Al-Sultan Perfumes',ship:'Delivery · 3–5 days',price:'235 SAR',diff:'+40 SAR'}]
  },

  bvlgari:{
    name:'Bvlgari Aqva Amara EDT',brand:'Bvlgari · 100ml · Eau de Toilette',
    img:YOURDIS_IMAGES.bvlgari,initials:'Bv',bg:'var(--b-blue)',
    name_ar:'بولغاري أكوا أمارا إي دي تي',brand_ar:'بولغاري · 100 مل · ماء تواليت',
    country:'Italy',country_ar:'إيطاليا',gender:'Men',gender_ar:'رجالي',
    family:'Citrus Aromatic',family_ar:'حمضي عطري',
    notes:'<span class="note-chip note-top">Top: Bitter Mandarin · Marine</span><span class="note-chip note-heart">Heart: Myrrh · Neroli</span><span class="note-chip note-base">Base: Ambergris · White Musk</span>',
    notes_ar:'قمة: ماندرين مرّ · بحري · قلب: مر · نيرولي · قاعدة: عنبر · مسك أبيض',
    desc:'Aqva Amara is a bolder, more complex evolution of the original Aqva. Bitter mandarin and a marine accord open with sharp energy before myrrh and neroli create an unusual Mediterranean heart. Ambergris and white musk carry it to a clean, lasting finish. Longevity 6–8 hours.',
    desc_ar:'تطور أجرأ وأكثر تعقيداً من الأكوا الأصلية. الماندرين المرّ والبحريات يفتحان بحيوية، ثم المر والنيرولي يخلقان قلباً متوسطياً غير عادي. يدوم 6-8 ساعات.',
    price:'215 SAR',orig:'265 SAR',store:'Najd Al-Otheyah',storeKey:'noon',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'190 SAR',avg:'240 SAR',ath:'285 SAR',
    rating:'4.3',reviews:'276',
    r1:'The bitter mandarin makes this completely different from other aquatics.',
    r2:'Great summer fragrance. Very unique opening.',
    priceHistory:[{date:'Today · 4 hrs ago',price:'215 SAR',dir:'down'},{date:'10 Mar 2025',price:'265 SAR',dir:'up'},{date:'25 Nov 2024',price:'200 SAR',dir:'down'},{date:'10 Aug 2024',price:'280 SAR',dir:'up'},{date:'01 May 2024',price:'225 SAR',dir:'down'}],
    storeComparison:[{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'215 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'235 SAR',diff:'+20 SAR'},{key:'sephora',name:'Asheq Al-Otor',ship:'Delivery · 3–5 days',price:'250 SAR',diff:'+35 SAR'}]
  },

  montblanc:{
    name:'Mont Blanc Explorer Platinum EDP',brand:'Mont Blanc · 100ml · EDP',
    img:YOURDIS_IMAGES.montblanc,initials:'Mp',bg:'var(--b-blue)',
    name_ar:'مونت بلانك إكسبلورر بلاتينيوم إي دي بي',brand_ar:'مونت بلانك · 100 مل · عطر مركّز',
    country:'France',country_ar:'فرنسا',gender:'Men',gender_ar:'رجالي',
    family:'Woody Fresh',family_ar:'خشبي منعش',
    notes:'<span class="note-chip note-top">Top: Bergamot · Apple</span><span class="note-chip note-heart">Heart: Vetiver · Cashmeran</span><span class="note-chip note-base">Base: Ambergris · Cedar</span>',
    notes_ar:'قمة: برغموت · تفاح · قلب: فيتيفر · كاشميران · قاعدة: عنبر · أرز',
    desc:'Explorer Platinum is cool, clean and supremely polished. Fresh bergamot and apple open brightly before vetiver and cashmeran bring textured, creamy warmth. Cedar and ambergris deliver a smooth, lasting base. Effortlessly wearable in any season. Longevity 7–9 hours.',
    desc_ar:'منعش ونظيف ومصقول للغاية. يفتح بالبرغموت والتفاح، ثم فيتيفر وكاشميران يضيفان دفئاً مخملياً. يدوم 7-9 ساعات.',
    price:'240 SAR',orig:'295 SAR',store:'Golden Scent',storeKey:'amazon',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'215 SAR',avg:'265 SAR',ath:'315 SAR',
    rating:'4.4',reviews:'334',
    r1:'The platinum version adds a smoothness and depth the original lacks.',
    r2:'Best value designer fragrance right now. Underrated.',
    priceHistory:[{date:'Today · 6 hrs ago',price:'240 SAR',dir:'down'},{date:'05 Mar 2025',price:'295 SAR',dir:'up'},{date:'10 Dec 2024',price:'225 SAR',dir:'down'},{date:'20 Aug 2024',price:'310 SAR',dir:'up'},{date:'01 May 2024',price:'250 SAR',dir:'down'}],
    storeComparison:[{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'240 SAR',diff:'Best price'},{key:'namshi',name:'Al-Sultan Perfumes',ship:'Free delivery · 2–3 days',price:'260 SAR',diff:'+20 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'280 SAR',diff:'+40 SAR'}]
  },

  valentino:{
    name:'Valentino Donna Born in Roma EDP',brand:'Valentino · 100ml · EDP',
    img:YOURDIS_IMAGES.valentino,initials:'Vd',bg:'var(--b-purple)',
    name_ar:'فالنتينو دونا بورن إن روما إي دي بي',brand_ar:'فالنتينو · 100 مل · عطر مركّز',
    country:'Italy',country_ar:'إيطاليا',gender:'Women',gender_ar:'نسائي',
    family:'Floral Woody',family_ar:'زهري خشبي',
    notes:'<span class="note-chip note-top">Top: Mandarin · Blackcurrant Bud</span><span class="note-chip note-heart">Heart: Jasmine · Bourbon Vanilla</span><span class="note-chip note-base">Base: Vetiver · Virginia Cedar</span>',
    notes_ar:'قمة: ماندرين · برعم كشمش أسود · قلب: ياسمين · فانيليا بوربون · قاعدة: فيتيفر · أرز فيرجينيا',
    desc:'Born in Roma is a striking meeting of tradition and modernity. Blackcurrant bud and mandarin open with vibrant energy before an opulent jasmine and bourbon vanilla heart unfolds. Virginia cedar and vetiver ground it with natural elegance. Longevity 8–10 hours.',
    desc_ar:'لقاء مذهل بين التقليد والحداثة. برعم الكشمش والماندرين يفتحان بحيوية، ثم قلب فاخر من الياسمين وفانيليا بوربون. يدوم 8-10 ساعات.',
    price:'315 SAR',orig:'390 SAR',store:'Asheq Al-Otor',storeKey:'sephora',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'285 SAR',avg:'360 SAR',ath:'415 SAR',
    rating:'4.5',reviews:'418',
    r1:'The jasmine is incredibly realistic and the vanilla is not too sweet.',
    r2:'Feminine but sophisticated. Perfect for evening events.',
    priceHistory:[{date:'Today · 2 hrs ago',price:'315 SAR',dir:'down'},{date:'20 Feb 2025',price:'390 SAR',dir:'up'},{date:'05 Nov 2024',price:'300 SAR',dir:'down'},{date:'01 Aug 2024',price:'405 SAR',dir:'up'},{date:'15 Apr 2024',price:'325 SAR',dir:'down'}],
    storeComparison:[{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'315 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'338 SAR',diff:'+23 SAR'},{key:'noon',name:'Najd Al-Otheyah',ship:'Delivery · 3–5 days',price:'360 SAR',diff:'+45 SAR'}]
  },

  carolinaherrera:{
    name:'Carolina Herrera Good Girl EDP',brand:'Carolina Herrera · 80ml · EDP',
    img:YOURDIS_IMAGES.carolinaherrera,initials:'Gg',bg:'var(--b-sage)',
    name_ar:'كارولينا هيريرا غود غيرل إي دي بي',brand_ar:'كارولينا هيريرا · 80 مل · عطر مركّز',
    country:'USA',country_ar:'الولايات المتحدة',gender:'Women',gender_ar:'نسائي',
    family:'Floral Gourmand',family_ar:'زهري شهي',
    notes:'<span class="note-chip note-top">Top: Almond · Coffee · Bergamot</span><span class="note-chip note-heart">Heart: Jasmine · Tuberose</span><span class="note-chip note-base">Base: Tonka Bean · Cocoa · Sandalwood</span>',
    notes_ar:'قمة: لوز · قهوة · برغموت · قلب: ياسمين · تيوبروز · قاعدة: تونكا · كاكاو · صندل',
    desc:'Good Girl is an iconic duality — provocative yet refined. Coffee and almond create a dark, roasted opening before jasmine and tuberose bloom into the heart. Tonka bean and cocoa wrap it in a warm, sensual base. Longevity 10+ hours.',
    desc_ar:'ثنائية أيقونية — مثيرة وأنيقة. القهوة واللوز يفتحان بشكل محمّص داكن، ثم الياسمين والتيوبروز يتفتحان. التونكا والكاكاو يلفّانه بقاعدة دافئة وحسية. يدوم 10 ساعات وأكثر.',
    price:'350 SAR',orig:'430 SAR',store:'Al-Sultan Perfumes',storeKey:'namshi',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'320 SAR',avg:'395 SAR',ath:'455 SAR',
    rating:'4.6',reviews:'895',
    r1:'The coffee note makes this completely unique. Gets compliments constantly.',
    r2:'Dark and sensual without being heavy. Perfect for evenings.',
    priceHistory:[{date:'Today · 3 hrs ago',price:'350 SAR',dir:'down'},{date:'10 Mar 2025',price:'430 SAR',dir:'up'},{date:'15 Nov 2024',price:'335 SAR',dir:'down'},{date:'01 Sep 2024',price:'445 SAR',dir:'up'},{date:'20 May 2024',price:'360 SAR',dir:'down'}],
    storeComparison:[{key:'namshi',name:'Al-Sultan Perfumes',ship:'Free delivery · 1–2 days',price:'350 SAR',diff:'Best price'},{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'375 SAR',diff:'+25 SAR'},{key:'amazon',name:'Golden Scent',ship:'Delivery · 3–5 days',price:'400 SAR',diff:'+50 SAR'}]
  },

  narciso:{
    name:'Narciso Rodriguez For Her EDP',brand:'Narciso Rodriguez · 100ml · EDP',
    img:YOURDIS_IMAGES.narciso,initials:'Nr',bg:'var(--b-pink)',
    name_ar:'نارسيسو رودريغيز فور هير إي دي بي',brand_ar:'نارسيسو رودريغيز · 100 مل · عطر مركّز',
    country:'USA',country_ar:'الولايات المتحدة',gender:'Women',gender_ar:'نسائي',
    family:'Floral Musky',family_ar:'زهري مسكي',
    notes:'<span class="note-chip note-top">Top: Osmanthus · Rose</span><span class="note-chip note-heart">Heart: Musk · Heliotrope</span><span class="note-chip note-base">Base: Sandalwood · Amber</span>',
    notes_ar:'قمة: أوسمانثوس · ورد · قلب: مسك · هيليوتروب · قاعدة: صندل · عنبر',
    desc:'One of the most perfectly composed musky florals ever made. Osmanthus and rose open softly before a clean, warm musk becomes the true soul of the fragrance. Sandalwood and amber create a seamless, skin-like base. Longevity 8–10 hours.',
    desc_ar:'أحد أكثر العطور الزهرية المسكية المركّبة بشكل مثالي. الأوسمانثوس والورد يفتحان بنعومة قبل أن يصبح المسك الدافئ روح العطر. يدوم 8-10 ساعات.',
    price:'280 SAR',orig:'345 SAR',store:'Golden Scent',storeKey:'amazon',
    badge:'↓ 19% off',badgeClass:'badge-good',
    atl:'255 SAR',avg:'315 SAR',ath:'370 SAR',
    rating:'4.5',reviews:'521',
    r1:'The musk is skin-close and incredibly intimate. One of the best skin-scents.',
    r2:'Understated elegance. Perfect for when you want to smell like yourself — but better.',
    priceHistory:[{date:'Today · 1 hr ago',price:'280 SAR',dir:'down'},{date:'15 Feb 2025',price:'345 SAR',dir:'up'},{date:'01 Nov 2024',price:'265 SAR',dir:'down'},{date:'10 Jul 2024',price:'360 SAR',dir:'up'},{date:'20 Mar 2024',price:'290 SAR',dir:'down'}],
    storeComparison:[{key:'amazon',name:'Golden Scent',ship:'Free delivery · 1–2 days',price:'280 SAR',diff:'Best price'},{key:'sephora',name:'Asheq Al-Otor',ship:'Free delivery · 2–3 days',price:'300 SAR',diff:'+20 SAR'},{key:'namshi',name:'Al-Sultan Perfumes',ship:'Delivery · 3–5 days',price:'325 SAR',diff:'+45 SAR'}]
  },

  dunhill:{
    name:'Dunhill Desire Blue EDT',brand:'Dunhill · 100ml · Eau de Toilette',
    img:YOURDIS_IMAGES.dunhill,initials:'Db',bg:'var(--b-blue)',
    name_ar:'دانهيل ديزاير بلو إي دي تي',brand_ar:'دانهيل · 100 مل · ماء تواليت',
    country:'UK',country_ar:'المملكة المتحدة',gender:'Men',gender_ar:'رجالي',
    family:'Fresh Aquatic',family_ar:'مائي منعش',
    notes:'<span class="note-chip note-top">Top: Bergamot · Sea Accord · Lemon</span><span class="note-chip note-heart">Heart: Geranium · Ginger</span><span class="note-chip note-base">Base: Amber · Sandalwood · Musk</span>',
    notes_ar:'قمة: برغموت · ألحان بحرية · ليمون · قلب: جيرانيوم · زنجبيل · قاعدة: عنبر · صندل · مسك',
    desc:'Desire Blue is a crisp, elegant aquatic that stands out in its category. Bergamot, sea accord and lemon create a sparkling marine-fresh opening before ginger and geranium add spiced warmth. The base is clean and grounding. Outstanding value. Longevity 6–8 hours.',
    desc_ar:'منعش وأنيق ومائي يتميز في فئته. البرغموت والألحان البحرية والليمون يخلقون افتتاحاً بحرياً متألقاً، ثم الزنجبيل والجيرانيوم يضيفان دفئاً. قيمة ممتازة. يدوم 6-8 ساعات.',
    price:'145 SAR',orig:'185 SAR',store:'Najd Al-Otheyah',storeKey:'noon',
    badge:'↓ 22% off',badgeClass:'badge-fire',
    atl:'130 SAR',avg:'165 SAR',ath:'200 SAR',
    rating:'4.2',reviews:'248',
    r1:'Incredible value. Punches well above its price point.',
    r2:'Fresh, clean and very wearable daily. The best budget aquatic in Saudi stores.',
    priceHistory:[{date:'Today · 5 hrs ago',price:'145 SAR',dir:'down'},{date:'28 Feb 2025',price:'185 SAR',dir:'up'},{date:'15 Nov 2024',price:'135 SAR',dir:'down'},{date:'01 Aug 2024',price:'195 SAR',dir:'up'},{date:'10 Apr 2024',price:'150 SAR',dir:'down'}],
    storeComparison:[{key:'noon',name:'Najd Al-Otheyah',ship:'Free delivery · 1–2 days',price:'145 SAR',diff:'Best price'},{key:'amazon',name:'Golden Scent',ship:'Free delivery · 2–3 days',price:'160 SAR',diff:'+15 SAR'},{key:'jarir',name:'V Perfume',ship:'Delivery · 3–5 days',price:'175 SAR',diff:'+30 SAR'}]
  }

};

var BRANDS = {
  chanel:{name:'Chanel',initials:'Cn',bg:'var(--b-purple)',origin:'France · Founded 1910',frags:'22 fragrances',best:'Best: 410 SAR',products:[{key:'chanel',name:'Bleu de Chanel EDP',sub:'100ml · EDP',price:'485 SAR',badge:'↓ 22% off',badgeClass:'badge-fire',img:YOURDIS_IMAGES.chanel,imgBg:'var(--b-purple)',ini:'Cd'},{key:'chanel',name:'Bleu de Chanel EDT',sub:'100ml · EDT',price:'410 SAR',badge:'↗ Good',badgeClass:'badge-good',img:YOURDIS_IMAGES.chanel,imgBg:'var(--b-purple)',ini:'Cd'}]},
  dior:{name:'Dior',initials:'Dr',bg:'var(--b-teal)',origin:'France · Founded 1946',frags:'31 fragrances',best:'Best: 295 SAR',products:[{key:'dior',name:'Sauvage EDT',sub:'200ml · EDT',price:'310 SAR',badge:'↓ 16% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Dk'},{key:'dior',name:'Sauvage Elixir',sub:'60ml · Elixir',price:'420 SAR',badge:'↓ 12% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Dk'}]},
  tomford:{name:'Tom Ford',initials:'Tf',bg:'var(--b-amber)',origin:'USA · Founded 2006',frags:'26 fragrances',best:'Best: 490 SAR',products:[{key:'tomford',name:'Tobacco Oud EDP',sub:'50ml · EDP',price:'590 SAR',badge:'↓ 9% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.tomford,imgBg:'var(--b-amber)',ini:'Tf'}]},
  ysl:{name:'YSL',initials:'YS',bg:'var(--b-pink)',origin:'France · Founded 1961',frags:'15 fragrances',best:'Best: 270 SAR',products:[{key:'ysl',name:'Y Le Parfum',sub:'60ml · EDP',price:'290 SAR',badge:'↓ 17% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.ysl,imgBg:'var(--b-pink)',ini:'YS'}]},
  armani:{name:'Armani',initials:'Ar',bg:'var(--b-blue)',origin:'Italy · Founded 1975',frags:'18 fragrances',best:'Best: 265 SAR',products:[{key:'armani',name:'Acqua di Gio EDP',sub:'75ml · EDP',price:'265 SAR',badge:'↓ 24% off',badgeClass:'badge-fire',img:YOURDIS_IMAGES.armani,imgBg:'var(--b-blue)',ini:'Aq'},{key:'armani',name:'Acqua di Gio Profumo',sub:'75ml · Parfum',price:'395 SAR',badge:'↓ 11% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.armani,imgBg:'var(--b-blue)',ini:'Aq'}]},
  creed:{name:'Creed',initials:'Cr',bg:'var(--b-sage)',origin:'UK · Founded 1760',frags:'9 fragrances',best:'Best: 840 SAR',products:[{key:'creed',name:'Creed Aventus',sub:'100ml · EDP',price:'840 SAR',badge:'↓ 20% off',badgeClass:'badge-fire',img:YOURDIS_IMAGES.creed,imgBg:'var(--b-sage)',ini:'Cr'}]},
  versace:{name:'Versace',initials:'Vs',bg:'var(--b-pink)',origin:'Italy · Founded 1978',frags:'14 fragrances',best:'Best: 345 SAR',products:[{key:'versace',name:'Eros EDP',sub:'100ml · EDP',price:'345 SAR',badge:'↓ 18% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.versace,imgBg:'var(--b-pink)',ini:'Ve'}]},
  burberry:{name:'Burberry',initials:'Bb',bg:'var(--b-teal)',origin:'UK · Founded 1856',frags:'12 fragrances',best:'Best: 280 SAR',products:[{key:'burberry',name:'Hero EDP',sub:'100ml · EDP',price:'280 SAR',badge:'↓ 18% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.burberry,imgBg:'var(--b-teal)',ini:'Bh'}]},
  hermes:{name:'Hermes',initials:'Hr',bg:'var(--b-amber)',origin:'France · Founded 1837',frags:'8 fragrances',best:'Best: 380 SAR',products:[{key:'hermes',name:'Terre dHermes EDP',sub:'75ml · EDP',price:'380 SAR',badge:'↓ 17% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.hermes,imgBg:'var(--b-amber)',ini:'Hr'}]},
  guerlain:{name:'Guerlain',initials:'Gu',bg:'var(--b-sage)',origin:'France · Founded 1828',frags:'14 fragrances',best:'Best: 270 SAR',products:[{key:'guerlain',name:'Mon Guerlain EDP',sub:'100ml · EDP',price:'270 SAR',badge:'↓ 18% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.guerlain,imgBg:'var(--b-sage)',ini:'Gu'}]},
  memo:{name:'Memo Paris',initials:'Mm',bg:'var(--b-pink)',origin:'France · Founded 2007',frags:'7 fragrances',best:'Best: 510 SAR',products:[{key:'chanel',name:'Irish Leather',sub:'75ml · EDP',price:'510 SAR',badge:'In Stock',badgeClass:'badge-neutral',img:YOURDIS_IMAGES.chanel,imgBg:'var(--b-pink)',ini:'Mm'}]},
  acqua:{name:'Acqua di Parma',initials:'Aq',bg:'var(--b-teal)',origin:'Italy · Founded 1916',frags:'5 fragrances',best:'Best: 340 SAR',products:[{key:'dior',name:'Colonia',sub:'100ml · Cologne',price:'340 SAR',badge:'Good',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Aq'}]},
  givenchy:{name:'Givenchy',initials:'Gc',bg:'var(--b-pink)',origin:'France · Founded 1952',frags:'11 fragrances',best:'Best: 220 SAR',products:[{key:'dior',name:'Gentleman Boisee',sub:'100ml · EDP',price:'220 SAR',badge:'Good',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-pink)',ini:'Gc'}]},
  narciso:{name:'Narciso Rodriguez',initials:'Nk',bg:'var(--b-sage)',origin:'USA · Founded 1997',frags:'6 fragrances',best:'Best: 280 SAR',products:[{key:'narciso',name:'For Her EDP',sub:'100ml · EDP',price:'280 SAR',badge:'↓ 19% off',badgeClass:'badge-good',img:YOURDIS_IMAGES.narciso,imgBg:'var(--b-pink)',ini:'Nr'}]}
};

var STORES = {
  amazon:{name:'Golden Scent',initials:'Gs',bg:'var(--b-blue)',url:'goldenscent.com',frags:'280+',drops:'18',low:'95 SAR',deals:[{key:'chanel',name:'Bleu de Chanel EDP 100ml',brand:'Chanel',price:'485 SAR',orig:'620 SAR',badge:'↓ 22%',badgeClass:'badge-fire',img:YOURDIS_IMAGES.chanel,imgBg:'var(--b-purple)',ini:'Cd'},{key:'armani',name:'Acqua di Gio EDP 75ml',brand:'Armani',price:'265 SAR',orig:'350 SAR',badge:'↓ 24%',badgeClass:'badge-fire',img:YOURDIS_IMAGES.armani,imgBg:'var(--b-blue)',ini:'Aq'},{key:'dior',name:'Sauvage Elixir 60ml',brand:'Dior',price:'420 SAR',orig:'480 SAR',badge:'↓ 12%',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Dk'}]},
  namshi:{name:'Al-Sultan Perfumes',initials:'As',bg:'var(--b-teal)',url:'al-sultan.com',frags:'190+',drops:'11',low:'120 SAR',deals:[{key:'dior',name:'Dior Sauvage EDT 200ml',brand:'Dior',price:'310 SAR',orig:'370 SAR',badge:'↓ 16%',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Dk'},{key:'armani',name:'Acqua di Gio Profumo 75ml',brand:'Armani',price:'395 SAR',orig:'445 SAR',badge:'↓ 11%',badgeClass:'badge-good',img:YOURDIS_IMAGES.armani,imgBg:'var(--b-blue)',ini:'Aq'}]},
  sephora:{name:'Asheq Al-Otor',initials:'Ao',bg:'var(--b-pink)',url:'asheqalotor.com',frags:'450+',drops:'22',low:'110 SAR',deals:[{key:'tomford',name:'Tom Ford Tobacco Oud 50ml',brand:'Tom Ford',price:'590 SAR',orig:'650 SAR',badge:'↓ 9%',badgeClass:'badge-good',img:YOURDIS_IMAGES.tomford,imgBg:'var(--b-amber)',ini:'Tf'},{key:'chanel',name:'Bleu de Chanel Parfum 50ml',brand:'Chanel',price:'680 SAR',orig:'750 SAR',badge:'↓ 9%',badgeClass:'badge-good',img:YOURDIS_IMAGES.chanel,imgBg:'var(--b-purple)',ini:'Cd'}]},
  noon:{name:'Najd Al-Otheyah',initials:'No',bg:'var(--b-amber)',url:'najdalotheyah.com',frags:'210+',drops:'14',low:'115 SAR',deals:[{key:'ysl',name:'YSL Y Le Parfum 60ml',brand:'YSL',price:'290 SAR',orig:'350 SAR',badge:'↓ 17%',badgeClass:'badge-good',img:YOURDIS_IMAGES.ysl,imgBg:'var(--b-pink)',ini:'YS'},{key:'creed',name:'Creed Aventus 100ml',brand:'Creed',price:'840 SAR',orig:'1,050 SAR',badge:'↓ 20%',badgeClass:'badge-fire',img:YOURDIS_IMAGES.creed,imgBg:'var(--b-sage)',ini:'Cr'}]},
  centrepoint:{name:'Deraah',initials:'Dr',bg:'var(--b-sage)',url:'deraah.com',frags:'85+',drops:'5',low:'150 SAR',deals:[{key:'dior',name:'Dior Homme Sport EDT 100ml',brand:'Dior',price:'255 SAR',orig:'295 SAR',badge:'↓ 14%',badgeClass:'badge-good',img:YOURDIS_IMAGES.dior,imgBg:'var(--b-teal)',ini:'Dk'}]},
  jarir:{name:'V Perfume',initials:'Vp',bg:'var(--b-purple)',url:'vperfume.com',frags:'40+',drops:'3',low:'180 SAR',deals:[{key:'armani',name:'Acqua di Gio EdT 100ml',brand:'Armani',price:'180 SAR',orig:'215 SAR',badge:'↓ 16%',badgeClass:'badge-good',img:YOURDIS_IMAGES.armani,imgBg:'var(--b-blue)',ini:'Aq'}]}
};

var SEARCH_ITEMS = [
  {key:'chanel',name:'Bleu de Chanel EDP',brand:'Chanel',size:'150ml',store:'Golden Scent',price:'595 SAR',orig:'850 SAR',badge:'↓ Best Price',badgeClass:'badge-fire',bg:'var(--b-purple)',ini:'Cd',img:YOURDIS_IMAGES.chanel},
  {key:'chanel',name:'Bleu de Chanel EDP',brand:'Chanel',size:'100ml',store:'Kaneen',price:'485 SAR',orig:'620 SAR',badge:'↓ Excellent',badgeClass:'badge-fire',bg:'var(--b-purple)',ini:'Cd',img:YOURDIS_IMAGES.chanel},
  {key:'dior',name:'Dior Sauvage EDT',brand:'Dior',size:'200ml',store:'Namshi',price:'310 SAR',orig:null,badge:null,badgeClass:null,bg:'var(--b-teal)',ini:'Dk',img:YOURDIS_IMAGES.dior},
  {key:'armani',name:'Acqua di Gio EDP',brand:'Armani',size:'75ml',store:'Golden Scent',price:'265 SAR',orig:null,badge:null,badgeClass:null,bg:'var(--b-blue)',ini:'Aq',img:YOURDIS_IMAGES.armani},
  {key:'ysl',name:'YSL Y Le Parfum',brand:'YSL',size:'60ml',store:'V Perfume',price:'290 SAR',orig:null,badge:null,badgeClass:null,bg:'var(--b-pink)',ini:'YS',img:YOURDIS_IMAGES.ysl},
  {key:'tomford',name:'Tobacco Oud EDP',brand:'Tom Ford',size:'50ml',store:'Asheq Al-Otor',price:'590 SAR',orig:'650 SAR',badge:'↓ 9% off',badgeClass:'badge-good',bg:'var(--b-amber)',ini:'Tf',img:YOURDIS_IMAGES.tomford},
  {key:'creed',name:'Creed Aventus',brand:'Creed',size:'100ml',store:'Asheq Al-Otor',price:'840 SAR',orig:'1,050 SAR',badge:'↓ 20% off',badgeClass:'badge-fire',bg:'var(--b-sage)',ini:'Cr',img:YOURDIS_IMAGES.creed},
  {key:'versace',name:'Versace Eros EDP',brand:'Versace',size:'100ml',store:'Golden Scent',price:'345 SAR',orig:'420 SAR',badge:'↓ 18% off',badgeClass:'badge-good',bg:'var(--b-pink)',ini:'Ve',img:YOURDIS_IMAGES.versace},
  {key:'burberry',name:'Burberry Hero EDP',brand:'Burberry',size:'100ml',store:'Al-Sultan Perfumes',price:'280 SAR',orig:'340 SAR',badge:'↓ 18% off',badgeClass:'badge-good',bg:'var(--b-teal)',ini:'Bh',img:YOURDIS_IMAGES.burberry},
  {key:'paco',name:'1 Million EDP',brand:'Paco Rabanne',size:'100ml',store:'Asheq Al-Otor',price:'320 SAR',orig:'395 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-amber)',ini:'1M',img:YOURDIS_IMAGES.paco},
  {key:'lancome',name:'Idole EDP',brand:'Lancome',size:'75ml',store:'Golden Scent',price:'295 SAR',orig:'370 SAR',badge:'↓ 20% off',badgeClass:'badge-good',bg:'var(--b-purple)',ini:'Id',img:YOURDIS_IMAGES.lancome},
  {key:'hermes',name:'Terre dHermes EDP',brand:'Hermes',size:'75ml',store:'Asheq Al-Otor',price:'380 SAR',orig:'455 SAR',badge:'↓ 17% off',badgeClass:'badge-good',bg:'var(--b-amber)',ini:'Hr',img:YOURDIS_IMAGES.hermes},
  {key:'guerlain',name:'Mon Guerlain EDP',brand:'Guerlain',size:'100ml',store:'Najd Al-Otheyah',price:'270 SAR',orig:'330 SAR',badge:'↓ 18% off',badgeClass:'badge-good',bg:'var(--b-sage)',ini:'Gu',img:YOURDIS_IMAGES.guerlain},
  {key:'jpgaultier',name:'Le Male EDP',brand:'Jean Paul Gaultier',size:'75ml',store:'Asheq Al-Otor',price:'260 SAR',orig:'320 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-pink)',ini:'LM',img:YOURDIS_IMAGES.jpgaultier},
  {key:'isseymiyake',name:'Leau dIssey EDT',brand:'Issey Miyake',size:'100ml',store:'V Perfume',price:'195 SAR',orig:'245 SAR',badge:'↓ 20% off',badgeClass:'badge-good',bg:'var(--b-teal)',ini:'Iy',img:YOURDIS_IMAGES.isseymiyake},
  {key:'bvlgari',name:'Aqva Amara EDT',brand:'Bvlgari',size:'100ml',store:'Najd Al-Otheyah',price:'215 SAR',orig:'265 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-blue)',ini:'Bv',img:YOURDIS_IMAGES.bvlgari},
  {key:'montblanc',name:'Explorer Platinum EDP',brand:'Mont Blanc',size:'100ml',store:'Golden Scent',price:'240 SAR',orig:'295 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-blue)',ini:'Mp',img:YOURDIS_IMAGES.montblanc},
  {key:'valentino',name:'Donna Born in Roma EDP',brand:'Valentino',size:'100ml',store:'Asheq Al-Otor',price:'315 SAR',orig:'390 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-purple)',ini:'Vd',img:YOURDIS_IMAGES.valentino},
  {key:'carolinaherrera',name:'Good Girl EDP',brand:'Carolina Herrera',size:'80ml',store:'Al-Sultan Perfumes',price:'350 SAR',orig:'430 SAR',badge:'↓ 19% off',badgeClass:'badge-good',bg:'var(--b-sage)',ini:'Gg',img:YOURDIS_IMAGES.carolinaherrera},
  {key:'dunhill',name:'Desire Blue EDT',brand:'Dunhill',size:'100ml',store:'Najd Al-Otheyah',price:'145 SAR',orig:'185 SAR',badge:'↓ 22% off',badgeClass:'badge-fire',bg:'var(--b-blue)',ini:'Db',img:YOURDIS_IMAGES.dunhill}
];

